# Generated by Django 5.2.16 on 2026-07-10 08:29

import django.utils.timezone
from django.db import migrations, models
from django.utils.translation import gettext_lazy as _


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RandomModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When this row was first created.",
                        verbose_name=_("created at"),
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this row was last updated.",
                        verbose_name=_("updated at"),
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Inclusive start of the range.",
                        verbose_name=_("start date"),
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="Exclusive-style end bound used by the check constraint.",
                        verbose_name=_("end date"),
                    ),
                ),
            ],
            options={
                "verbose_name": _("random model"),
                "verbose_name_plural": _("random models"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("start_date__lt", models.F("end_date"))),
                        name="start_date_before_end_date",
                    )
                ],
            },
        ),
    ]
