version: "3.9"

services:

  db:
    image: postgres:17.10
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB={{cookiecutter.project_slug}}
      - POSTGRES_USER={{cookiecutter.postgres_user}}
      - POSTGRES_PASSWORD={{cookiecutter.postgres_password}}
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U {{cookiecutter.postgres_user}} -d {{cookiecutter.project_slug}}"]
      interval: 5s
      timeout: 5s
      retries: 5

{%- if cookiecutter.use_pgadmin == "y" %}
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 'pg_pass'
    ports:
      - "5050:80"

{%- endif %}
{%- if cookiecutter.use_rabbitmq == "y" %}
  rabbitmq:
    image: "rabbitmq:alpine"
    container_name: rabbitmq
    ports:
      - 5672:5672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

{%- endif %}
{%- if cookiecutter.use_redis == "y" %}
  redis:
    image: redis:7.4.9
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

{%- endif %}

volumes:
    postgres-data:
{%- if cookiecutter.use_redis == "y" %}
    redis-data:
{%- endif %}
